name: Run Pester tests on Ubuntu
on: [push, pull_request]
jobs:
  pester-test:
    name: Run Pester tests
    runs-on: [ubuntu-latest, windows-2019, windows-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installs dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module psPAS, CredentialRetriever, Microsoft.PowerShell.SecretManagement
      - name: Executes Pester tests
        shell: pwsh
        run: |
          Import-Module Microsoft.PowerShell.SecretManagement -Force
          Invoke-Pester ./SecretManagement.CyberArk/Tests/*.Tests.ps1 -Passthru
